### ISSUE TITLE
AssertionError: self.obs_key_sample needs to be set

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#158]
@davidsebfischer I haven't quite wrapped my head around how the newly introduced attributes `self.bio_sample_obs_key` and `self.tech_sample_obs_key` relate to `self.obs_key_sample` and where the below error comes from. Could you briefly explain?

I hit this when I run load_all() on a daasetsupergroupsfaira that was subset to HCL datasets

```pytb
using python multiprocessing (processes=2), for easier debugging revert to sequential execution (processes=1)

/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py:383: UserWarning: using default genome Homo_sapiens_GRCh38_97
  warnings.warn(f"using default genome {genome}")
/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py:342: UserWarning: Cached loading enabled, but cache file /storage/groups/ml01/datasets/projects/20200101_Various_SfairaDataRepository_leander.dony/d10_1038_s41586_020_2157_4/cache/human_adiposetissueofabdominalregion_2020_None_han_001_10_1038_s41586-020-2157-4.h5ad not found. Loading from raw files.
  warnings.warn(f"Cached loading enabled, but cache file {filename} not found. "
/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py:383: UserWarning: using default genome Homo_sapiens_GRCh38_97
  warnings.warn(f"using default genome {genome}")
/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py:342: UserWarning: Cached loading enabled, but cache file /storage/groups/ml01/datasets/projects/20200101_Various_SfairaDataRepository_leander.dony/d10_1038_s41586_020_2157_4/cache/human_fallopiantube_2020_None_han_015_10_1038_s41586-020-2157-4.h5ad not found. Loading from raw files.
  warnings.warn(f"Cached loading enabled, but cache file {filename} not found. "
/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/dataloaders/loaders/d10_1038_s41586_020_2157_4/human_x_2020_microwellseq_han_x.py:285: FutureWarning: Your version of xlrd is 1.2.0. In xlrd >= 2.0, only the xls format is supported. As a result, the openpyxl engine will be used if it is installed and the engine argument is not specified. Install openpyxl instead.
  fig1_anno = pd.read_excel(
/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/dataloaders/loaders/d10_1038_s41586_020_2157_4/human_x_2020_microwellseq_han_x.py:285: FutureWarning: Your version of xlrd is 1.2.0. In xlrd >= 2.0, only the xls format is supported. As a result, the openpyxl engine will be used if it is installed and the engine argument is not specified. Install openpyxl instead.
  fig1_anno = pd.read_excel(
/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py:342: UserWarning: Cached loading enabled, but cache file /storage/groups/ml01/datasets/projects/20200101_Various_SfairaDataRepository_leander.dony/d10_1038_s41586_020_2157_4/cache/human_lung_2020_None_han_029_10_1038_s41586-020-2157-4.h5ad not found. Loading from raw files.
  warnings.warn(f"Cached loading enabled, but cache file {filename} not found. "
/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py:342: UserWarning: Cached loading enabled, but cache file /storage/groups/ml01/datasets/projects/20200101_Various_SfairaDataRepository_leander.dony/d10_1038_s41586_020_2157_4/cache/human_spleen_2020_None_han_043_10_1038_s41586-020-2157-4.h5ad not found. Loading from raw files.
  warnings.warn(f"Cached loading enabled, but cache file {filename} not found. "
/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py:342: UserWarning: Cached loading enabled, but cache file /storage/groups/ml01/datasets/projects/20200101_Various_SfairaDataRepository_leander.dony/d10_1038_s41586_020_2157_4/cache/human_umbilicalcordblood_2020_None_han_057_10_1038_s41586-020-2157-4.h5ad not found. Loading from raw files.
  warnings.warn(f"Cached loading enabled, but cache file {filename} not found. "
/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py:342: UserWarning: Cached loading enabled, but cache file /storage/groups/ml01/datasets/projects/20200101_Various_SfairaDataRepository_leander.dony/d10_1038_s41586_020_2157_4/cache/human_ovary_2020_None_han_071_10_1038_s41586-020-2157-4.h5ad not found. Loading from raw files.
  warnings.warn(f"Cached loading enabled, but cache file {filename} not found. "
/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py:342: UserWarning: Cached loading enabled, but cache file /storage/groups/ml01/datasets/projects/20200101_Various_SfairaDataRepository_leander.dony/d10_1038_s41586_020_2157_4/cache/human_testis_2020_None_han_085_10_1038_s41586-020-2157-4.h5ad not found. Loading from raw files.
  warnings.warn(f"Cached loading enabled, but cache file {filename} not found. "
/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py:342: UserWarning: Cached loading enabled, but cache file /storage/groups/ml01/datasets/projects/20200101_Various_SfairaDataRepository_leander.dony/d10_1038_s41586_020_2157_4/cache/human_thymus_2020_None_han_099_10_1038_s41586-020-2157-4.h5ad not found. Loading from raw files.
  warnings.warn(f"Cached loading enabled, but cache file {filename} not found. "

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/python/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/python/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py", line 39, in map_fn
    ds.load(
  File "/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py", line 400, in load
    self._load_cached(load_raw=load_raw, allow_caching=allow_caching)
  File "/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py", line 361, in _load_cached
    _cached_reading(self.cache_fn)
  File "/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py", line 344, in _cached_reading
    self.adata = self._load()
  File "/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py", line 1809, in _load
    self._load_from_group()
  File "/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py", line 1787, in _load_from_group
    assert self.bio_sample_obs_key is not None, "self.obs_key_sample needs to be set"
AssertionError: self.obs_key_sample needs to be set
"""

The above exception was the direct cause of the following exception:

AssertionError                            Traceback (most recent call last)
<ipython-input-5-ddb54d6a0daa> in <module>
----> 1 dssg.load_all(processes=2)

/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py in load_all(self, annotated_only, match_to_reference, remove_gene_version, load_raw, allow_caching, processes)
   2467         """
   2468         for x in self.dataset_groups:
-> 2469             x.load(
   2470                 annotated_only=annotated_only,
   2471                 remove_gene_version=remove_gene_version,

/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py in load(self, annotated_only, remove_gene_version, match_to_reference, load_raw, allow_caching, processes, func, kwargs_func)
   1909                   f"for easier debugging revert to sequential execution (processes=1)")
   1910             with multiprocessing.Pool(processes=processes) as pool:
-> 1911                 res = pool.starmap(map_fn, [
   1912                     (tuple([v] + args),)
   1913                     for k, v in self.datasets.items() if v.annotated or not annotated_only

/opt/python/lib/python3.8/multiprocessing/pool.py in starmap(self, func, iterable, chunksize)
    370         `func` and (a, b) becomes func(a, b).
    371         '''
--> 372         return self._map_async(func, iterable, starmapstar, chunksize).get()
    373 
    374     def starmap_async(self, func, iterable, chunksize=None, callback=None,

/opt/python/lib/python3.8/multiprocessing/pool.py in get(self, timeout)
    769             return self._value
    770         else:
--> 771             raise self._value
    772 
    773     def _set(self, i, obj):

AssertionError: self.obs_key_sample needs to be set
```

**Comment by davidsebfischer** [comment]
See also the discussion on the dropping this class here: https://github.com/theislab/sfaira/issues/141
