### ISSUE TITLE
Cannot convert integer scalar

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#250]
During data store writing we hit this super strange bug again:
```
SCRIPT loading human_retina_2019_10xsequencing_menon_001_10.1038/s41467-019-12780-8
SCRIPT loading human_thymus_2020_10xsequencing_park_001_10.1126/science.aay3224
SCRIPT loading human_prostategland_2018_10xsequencing_henry_001_10.1016/j.celrep.2018.11.086
SCRIPT loading human_None_2020_scirnaseq_cao_001_10.1126/science.aba7721
Traceback (most recent call last):
  File "/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/utils_scripts/write_store.py", line 20, in <module>
    ds.streamline_features(
  File "/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base/dataset.py", line 633, in streamline_features
    x_new[:, idx_feature_map[i:i + step]] = x[:, i:i + step]
  File "/opt/python/lib/python3.8/site-packages/scipy/sparse/_index.py", line 116, in __setitem__
    self._set_arrayXarray_sparse(i, j, x)
  File "/opt/python/lib/python3.8/site-packages/scipy/sparse/compressed.py", line 807, in _set_arrayXarray_sparse
    self._zero_many(*self._swap((row, col)))
  File "/opt/python/lib/python3.8/site-packages/scipy/sparse/compressed.py", line 927, in _zero_many
    ret = csr_sample_offsets(M, N, self.indptr, self.indices, n_samples,
ValueError: could not convert integer scalar
```
We already copy the matrix over in chunks to circumvent this issue (was fine like this for a year now):
https://github.com/theislab/sfaira/blob/5b0a7b984017bb02a2bf1f1186c82a94481826a6/sfaira/data/base/dataset.py#L626-L634

I'll try and reduce step size and see if this goes away again (human_None_2020_scirnaseq_cao_001_10.1126/science.aba7721 has a very large number of features I think, which could cause this to break again)

**Comment by le-ander** [comment]
step size of 500 seems to do the trick. this is something we should at some point fix properly though
