### ISSUE TITLE
Cannot download metadata for 10.1038/s41591-020-1061-7

### ISSUE THREAD

**Issue by alex-d13** [theislab/sfaira#668]
**Describe the bug**
I cannot download the metadata for the dataset with id: `homosapiens_blood_2020_10x5transcriptionprofiling_dengqing_001_10.1038/s41591-020-1061-7`

`urllib.error.HTTPError: HTTP Error 404: Not Found`

**To Reproduce**
```python
>>> import os
>>> basedir = '.'
>>> datadir = os.path.join(basedir, 'raw')
>>> metadir = os.path.join(basedir, 'meta')
>>> cachedir = os.path.join(basedir, 'cache')
>>> ds = sfaira.data.Universe(data_path=datadir, meta_path=metadir, cache_path=cachedir)
Ontology <class 'sfaira.versions.metadata.base.OntologyMondo'> is not a DAG, treat child-parent reasoning with care.
Ontology <class 'sfaira.versions.metadata.base.OntologyUberon'> is not a DAG, treat child-parent reasoning with care.
Ontology <class 'sfaira.versions.metadata.base.OntologyUberonLifecyclestage'> is not a DAG, treat child-parent reasoning with care.
>>> ds.subset(key="id", values=["homosapiens_blood_2020_10x5transcriptionprofiling_dengqing_001_10.1038/s41591-020-1061-7"]) 
>>> ds.datasets
{'homosapiens_blood_2020_10x5transcriptionprofiling_dengqing_001_10.1038/s41591-020-1061-7': <sfaira.data.dataloaders.base.dataset.DatasetBase object at 0x7fc842eef4f0>}
>>> ds.download()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/home/students/adietrich/.cache/R/basilisk/1.4.0/SimBu/0.99.6/SimBu_env_0_99_4/lib/python3.9/site-packages/sfaira/data/dataloaders/base/dataset_group.py", line 964, in download
    x.download(**kwargs)
  File "/nfs/home/students/adietrich/.cache/R/basilisk/1.4.0/SimBu/0.99.6/SimBu_env_0_99_4/lib/python3.9/site-packages/sfaira/data/dataloaders/base/dataset_group.py", line 404, in download
    v.download(**kwargs)
  File "/nfs/home/students/adietrich/.cache/R/basilisk/1.4.0/SimBu/0.99.6/SimBu_env_0_99_4/lib/python3.9/site-packages/sfaira/data/dataloaders/base/dataset.py", line 395, in download
    if 'Content-Disposition' in urllib.request.urlopen(url).info().keys():
  File "/nfs/home/students/adietrich/.cache/R/basilisk/1.4.0/SimBu/0.99.6/SimBu_env_0_99_4/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/nfs/home/students/adietrich/.cache/R/basilisk/1.4.0/SimBu/0.99.6/SimBu_env_0_99_4/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/nfs/home/students/adietrich/.cache/R/basilisk/1.4.0/SimBu/0.99.6/SimBu_env_0_99_4/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/nfs/home/students/adietrich/.cache/R/basilisk/1.4.0/SimBu/0.99.6/SimBu_env_0_99_4/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/nfs/home/students/adietrich/.cache/R/basilisk/1.4.0/SimBu/0.99.6/SimBu_env_0_99_4/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/nfs/home/students/adietrich/.cache/R/basilisk/1.4.0/SimBu/0.99.6/SimBu_env_0_99_4/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Expected behavior**

**System [please complete the following information]:**
 - OS: e.g. Ubuntu 18.04.6
 - Language Version: Python 3.9
 - Virtual environment: Conda
 - Sfaira version: 0.3.12

**Additional context**

The data file can be downloaded, a `GSE151511_RAW.tar` file is downloaded into the raw folder. Only the metadata link seems to be stuck. 
What I find strange is that the link seems to be working if i try to request it outside of sfaira:

```python
>>> ds.datasets['homosapiens_blood_2020_10x5transcriptionprofiling_dengqing_001_10.1038/s41591-020-1061-7'].download_url_meta
(['https://static-content.springer.com/esm/art%3A10.1038%2Fs41591-020-1061-7/MediaObjects/41591_2020_1061_MOESM3_ESM.xlsx'],)
>>> import requests
>>> requests.get('https://static-content.springer.com/esm/art%3A10.1038%2Fs41591-020-1061-7/MediaObjects/41591_2020_1061_MOESM3_ESM.xlsx').ok
True
```
I can also download this file manually and place it into the raw directory.

Is this behavior expected for some datasets? Should I then resort to downloading these files manually and then move on with `ds.load()`?

Thanks for your help,
Alex

**Comment by alex-d13** [comment]
I just realized that this dataset is flagged as not annotated:
```python
>>> ds.datasets['homosapiens_blood_2020_10x5transcriptionprofiling_dengqing_001_10.1038/s41591-020-1061-7'].annotated
False
```

**Comment by davidsebfischer** [comment]
So my first thought would be that you did not have a working or stable internet connection on the compute node on which you ran this? Could you or did you already try running the code on a laptop or local machine where you can ensure an internet connection?
