### ISSUE TITLE
Tensorflow is required but still in extra_requires

### ISSUE THREAD

**Issue by Zethson** [theislab/sfaira#70]
When installing the latest version (even human_data_loader_fixes branch) and attempting to import it I get:

```
>>> import sfaira
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zeth/PycharmProjects/sfaira/sfaira/__init__.py", line 24, in <module>
    import sfaira.models
  File "/home/zeth/PycharmProjects/sfaira/sfaira/models/__init__.py", line 2, in <module>
    from .pp_layer import PreprocInput
  File "/home/zeth/PycharmProjects/sfaira/sfaira/models/pp_layer.py", line 1, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
>>> 
```

Either Tensorflow must be moved to install requires or pp_layers cannot always be initialized when importing.

**Comment by davidsebfischer** [comment]
The plan is to make all tf imports local in functions, we do not want automatically install tensorflow because that can cause confusion with whether or not `tensorflow-gpu` is installed.

**Comment by Zethson** [comment]
Note:
I've added Tensorflow to the hard requirements. Else all workflows etc would constantly fail.

TF should be removed from the hard requirements to the tensorflow requirements as soon as @davidsebfischer plan is implemented.
